packages:
  - apps/*
  - packages/*
  - packages/configs/*

catalog:
  '@tailwindcss/postcss': ^4.1.18
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/node': ^25.0.3
  '@typescript-eslint/eslint-plugin': ^8.53.0
  '@typescript-eslint/parser': ^8.53.0
  autoprefixer: ^10.4.23
  eslint: ^8.57.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-react: ^7.34.0
  eslint-plugin-react-hooks: ^4.6.0
  postcss: ^8.5.6
  react: ^19.2.3
  react-dom: ^19.2.3
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
